export const IPC = {
  sessionSnapshot: 'session:snapshot',
  sessionStart: 'session:start',
  sessionPause: 'session:pause',
  sessionResume: 'session:resume',
  sessionComplete: 'session:complete',
  sessionUpdateSettings: 'session:update-settings',
  sessionUpdateNote: 'session:update-note',
  sessionEditSegments: 'session:edit-segments',
  sessionRecovery: 'session:recovery',
  historyList: 'history:list',
  historyDelete: 'history:delete',
  historyEditSegments: 'history:edit-segments',
  historyExportCsv: 'history:export-csv',
  settingsGet: 'settings:get',
  settingsSave: 'settings:save',
  windowShowMain: 'window:show-main',
  windowShowMini: 'window:show-mini',
  windowSetAlwaysOnTop: 'window:set-always-on-top',
} as const;
